android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

GROUP=app.warplink
POM_ARTIFACT_ID=sdk
VERSION_NAME=0.1.0-SNAPSHOT

POM_NAME=WarpLink Android SDK
POM_DESCRIPTION=Deep linking SDK for Android
POM_URL=https://github.com/AplnkTo/warplink-android-sdk
POM_SCM_URL=https://github.com/AplnkTo/warplink-android-sdk
POM_SCM_CONNECTION=scm:git:git://github.com/AplnkTo/warplink-android-sdk.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com:AplnkTo/warplink-android-sdk.git
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=warplink
POM_DEVELOPER_NAME=WarpLink
